---
output: word_document
---

Hi! You are invited to participate in a WISCIENCE-sponsored Spring Semester bookgroup for graduate students and postdocs in the sciences. We'll have 8 weekly sessions to read and discuss the 2011 book "Whistling Vivaldi: How stereotypes affect us and what we can do" by Claude Steele. 

Our informal book groups do not treat the book as "the truth", but as a way to give us a common experience from which to discuss the topics.  Volunteers from the group take turns on facilitation and in past book groups the discussion has been rated as one of the best parts.  People find it fun! While we haven't read this book, we are pretty excited by the potential for book group!  It combines research on stereotypes with practical advice for instruction.  The reviews are glowing!  The amazon.com site has customer reviews here: http://www.amazon.com/Whistling-Vivaldi-Stereotypes-Affect-Issues/dp/0393339726/




What you'll gain by participating: 

- Motivation to read a book you think will be useful to you  
- Hearing the ideas of others to amplify the benefit of reading ourselves   
- Learning community of graduate students & postdocs wrestling with similar dilemmas

Interested? Please reply by Friday, January 23 with the following information: 

- Name 
- Dept
- Academic status (Grad student or postdoc) and year of study  
- Which days can you meet noon to 1:00PM:   Tuesday, Wednesday, or Friday 
- Book purchase: Please choose:  

1. (I will buy the book myself) or 

2. (I would like to use a library copy) 

Please feel free to share this information with others who may want to participate.

Thanks,

Zak Handlos, handlos@wisc.edu, Graduate student in Atmospheric and Oceanic Sciences  
Fred Boehm, fred.boehm@wisc.edu, Graduate student in Statistics

